### ISSUE TITLE
Video not playing it can't be found 

### ISSUE THREAD

**Issue by ScripterSaurav** [chirag-droid/animeflix#12] opened 2021-11-26 07:05 UTC
Many anime videos are not playing after clicking on anime it shows Sorry, the anime video couldn't be found . Please fix this soon.

**Comment by chirag-droid** [comment] 2021-11-26 13:15
I don't upload anime videos, they come from another sites. Can you tell me what anime were you watching? 

Also if its adult content, it won't generally be there

**Comment by ScripterSaurav** [comment] 2021-11-26 13:56
> I don't upload anime videos, they come from another sites. Can you tell me what anime were you watching?
> 
> Also if its adult content, it won't generally be there

This [ Anime ](https://animeplix.vercel.app/watch/133965?episode=1) and many more are there's which are not Playing . use another site to scrap anime like gogoanime.cm to scrap anime.

**Comment by imlarx** [comment] 2021-11-28 14:29
@ScripterSaurav According to my analysis, `Komi-san wa, Komyushou desu.` seems to be working from the third-party provider used in this website. The issue is not from the third-party source but the third party source does not accept any type of punctuations. Mainly comma or `'s` as they can't be parsed properly. There isn't a fix for this as the anime data that is being fetched has punctuations on it.

**Comment by imlarx** [comment] 2021-11-28 14:30
> @ScripterSaurav According to my analysis, `Komi-san wa, Komyushou desu.` seems to be working from the third-party provider used in this website. The issue is not from the third-party source but the third party source does not accept any type of punctuations. Mainly comma or `'s` as they can't be parsed properly. There isn't a fix for this as the anime data that is being fetched has punctuations on it.

In regards to this. Any anime that has punctuations on them will not be parsed as it's not possible to scrape them from the source.

**Comment by chirag-droid** [comment] 2021-11-28 18:44
No, this isn't the case. I am using a function which parses it correctly. Its in `utility/utils.js`. The problem is on anilist the anime uses the word `Komyushu` and on gogoanime it uses the word `Comyushu`

**Comment by imlarx** [comment] 2021-11-29 06:29
Idk I missed out on small details haha...

**Comment by imlarx** [comment] 2021-11-29 08:04
@chirag-droid Also as I mentioned earlier in the email. I was trying to proxy gogoanime requests as you do on a different subdomain and it doesn't seem to be working. Do you mind telling me what exactly have you done about that? Anything is fine, either replying to the emails I sent you or by adding me on Discord. You can join [this server](https://discord.gg/vDzr8mBM8Q) and ping Delix.

**Closed** 2022-04-25 17:53 UTC
